Add custom response support
kandros/micro-jwt-auth pull request #10
Opened 2017-08-02 10:12 UTC by ronnyhaase

As I requested in #9

2017-08-02 10:13 UTC, ronnyhaase commented
I also considered custom HTTP code but thought anything else than 401 doesn't make sense, but it would be easy to add.
I'm not sure If I like the tests, it's a lot of repetition for that minor feature, maybe someone has a better idea?

2017-08-02 10:15 UTC, ronnyhaase commented on index.js
> +
I thought it's meaningful to turn `whitelist` to `config` so users don't have to pass an empty array if they want to pass a config but no whitelist.

2017-08-02 10:16 UTC, ronnyhaase commented on test/index.test.js
> +  const result = jwtAuth('mySecret', [], { resAuthInvalid: customRes })(() => {})(request, response)
With empty whitelist

2017-08-02 10:16 UTC, ronnyhaase commented on test/index.test.js
> +  const result = jwtAuth('mySecret', { resAuthMissing: customRes })()(request, response)
Skipping whitelist

2017-08-02 18:48 UTC, kandros commented on index.js
> +
yeah, I think whis is a good idea, I felt it coming when first introduced the whitelist parameter, but didn't wanted to overdue back then, i thinkg now it makes way more sense to have an options object

2017-08-02 18:52 UTC, ronnyhaase commented on test/index.test.js
> +  const result = jwtAuth('mySecret', [], { resAuthInvalid: customRes })(() => {})(request, response)
With (empty) whitelist

2017-08-02 18:52 UTC, ronnyhaase commented on test/index.test.js
> +  const result = jwtAuth('mySecret', { resAuthMissing: customRes })()(request, response)
Skipping whitelist

2017-08-02 18:53 UTC, kandros requested changes
This branch should be rebased on the version currently in master.

Please also update the readme to document this new feature.

Thanks :)

2017-08-02 21:53 UTC, ronnyhaase commented
OK, merged and updated README. I wasn't able to rebase, may you can squash when merging the PR.

2017-08-15 20:37 UTC, merged

2017-08-15 20:38 UTC, kandros commented
Hi Ronny, thank you for the help and sorry for they delay.

Updated version is now on npm